#!/usr/bin/env bash
# fixing issues when using docker

sudo apt-get update -y
sudo apt-get install -y apache2
sudo /etc/init.d/apache2 start
echo "Hello Holberton" | sudo tee -a /var/www/index.html
sudo /etc/init.d/apache2 restart
